
export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR="GET_PRODUCT_ERROR";

export const ADD_PRODUCT_REQUEST="ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR="ADD_PRODUCT_ERROR";

export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR="UPDATE_PRODUCT_ERROR";

export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR="DELETE_PRODUCT_ERROR";

export const GET_SINGLE_PRODUCT="GET_SINGLE_PRODUCT";
// export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
// export const GET_PRODUCT_ERROR="GET_PRODUCT_ERROR";

// Feedback action type
export const GET_FEEDBACK_REQUEST=" GET_FEEDBACK_REQUEST";
export const GET_FEEDBACK_SUCCESS=" GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_ERROR=" GET_FEEDBACK_ERROR";

export const DELETE_FEEDBACK_REQUEST=" DELETE_FEEDBACK_REQUEST";
export const DELETE_FEEDBACK_SUCCESS=" DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_ERROR=" DELETE_FEEDBACK_ERROR";

export const ADD_FEEDBACK_REQUEST="ADD_FEEDBACK_REQUEST";
export const ADD_FEEDBACK_SUCCESS="ADD_FEEDBACK_SUCCESS";
export const ADD_FEEDBACK_ERROR="ADD_FEEDBACK_ERROR";